# Logo
logo_image_source: http:overridden

# Index Page
index_banner_text: Override in blog!
index_banner_text_secondary: Override in blog (also icon css)!
index_font_awesome_icon_css: fa fa-magic

# Header
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  About: /about.html
  Contact: /contact.html

# Post
default_post_title: Untitled
default_post_icon: fa-file-text-o

# Archive Date Format
archive_date_format: YYYY MMM
archive_font_awesome_icon_css: fa-folder-open

# About Widget
about_widget_avatar_url: http://tachyons.io/img/avatar_1.jpg
about_widget_text: "Overridde along with avatar_url!"

# Comments.
comments:
  # Disqus comments
  disqus_shortname:

# Google Analytics Tracking ID
google_analytics:

# Social Media Platforms
social_platforms:
  - url: https://twitter.com/?lang=en
    fa_icon: fa-twitter
  - url: https://www.linkedin.com/
    fa_icon: fa-linkedin-in
  - url: https://www.facebook.com/
    fa_icon: fa-facebook
  - url: https://dribbble.com/
    fa_icon: fa-dribbble
  - url: https://github.com/
    fa_icon: fa-github
  - url: https://plus.google.com/
    fa_icon: fa-google-plus
  - url: https://www.behance.net/
    fa_icon: fa-behance
  - url: mailto:test@example.com
    fa_icon: fa-envelope
  - url: /#
    fa_icon: fa-rss
  - url: https://500px.com/
    fa_icon: fa-500px

# Footer about
footer_about: "Overridde!"
